sudo: required

services:
  - docker

language: python

script:
  - pytest -v yachting/yachting_back/tests.py

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test “$TRAVIS_BRANCH” = “development” && sh .travis/deploy_heroku.sh